language: java
jdk:
- openjdk8

script: "mvn deploy --settings settings.xml"
env:
  global:
  - secure: "iCtRGoUAN1V/djIaZhFrCkEWVvmR6aEy8yAdN4mNB3rny0yf93zCacz2fp4SRC2HNQiooTwjJyM93X/NQ5Jz6s8FIX+w6hE6acpAmG7KTklCEDTzBbiFlWZtUh/7SsL7DI+sxNXkUYYkZ3JvwSQS6aham+OGlaGPdpvPi/rQtdt2P0Xq0xvkEcJ7IfOC7VOsTixuSAHoZoDKUV/i4sXps/ovxOaCvqqdKDF/U9S3OSHTdqMOVwZR/r/jRhG8nqXN2ZY5hS08kFsh4a2+oa43t5k7TRYPAmpuhjR6EvvHrAfrFSaanpcwDTesER1pzb+933qveaP2R+XjTgS2g/f/xio1cNCyXjmIPlAHzMzcYdQYwClUEM0LOa8OqZg/YtYY739kp4nuPGl6sXm2WvMH3FH12K00NDmLgyp3hlvkFM3PEzO4uScYqSNBg/5mvE9lPHwrl7BuoYtV9rhYUkMLFBjaCp60Wl2WDf1zSTbTCf+bypgfMoVQ2JeamISsXTIrsLNTAVsaQEC4pCaCnsV5kq6lZe3F/HHElM066XYjD3b1HaZL0gYxZQebxLT4gfwAPyUDujzVvVXfvYDG4FXwhEwqNx2X/JuTwN8+dyx4sfhYNl7Z2J5dqLH5NdZUnPAYKV6ehdpU1UlTCaXTX9FOMEGBs6kj5AfpUWceG5voZqk="
  - secure: "qJL9RcJOAqQCB0WIVJ8QhodO/0+mhmXkYa3/X1zWGA5JGqUm7VF6+nagecxO8GkaQOscCR6f/npX5DJ+zXqrlI9bX7chXzGsGbVrHP7k2pdcMHQuCRnqnhrL2fsEArd7RS3FLYzPkqO69yMo0JgKSUULoMdFJBgNMgJRSKLVtxqKGvA5pzfILpVv9kjONJUDvcKHeyyJ3w05Cms4dkwWPDgDbx9x3DlB/NoN6xKjtVO1ZD3F0PkV6Ref7XYB74bZeTRekP1lBDw6Q2ChjY2VOCsFfHLiBeY6XmqM86CUKsidsOJsOEGhmzgpmc3GGuc40r+yj+J4UapcqFZAC43em4C2wkN21R5SHdLTJU72c6evSoND7peGj41juwZsAeRF6IQCTfY5C1k6eFm+AgyJXhNZXbBpfOrF6HWud/J9iKOSj+4SYLo33smrGWCFW7/MT5KYja4hVJ+RxvA0FGAc/XZmj4S6CXiD6sRtBarYfinrZIoTKeEEgkYkb0Wmxdj4VE/BJHdwmLtZ+2GYxySs8lsEnIc5pG3Ll0umHwIrb7Vk+l2/aQ5QHUijNd69XIMQrcURvgeRrRMcQ9nHuYiRqPE++kFlma+PDMqgmE+GnY94HKh238z3PRjfDIxP0aOXxaBVhD7rof80qBdF9HGkZJ1/JPc8c/6evzvHUG68cpY="
deploy:
  provider: releases
  api_key: 
    secure: "IhXyL+gl7gED9Ji0hA8iUl2BJi2wuEQ3efROmtSBrU3RqXlt1SEa703HcqRL/N/6IT3sdn0XfyktR70baXwpTjvX+V1ZHxeQNULY26wZ+ewEN23r9RxvcErpM4KBGa35+Jyy96GaXN34ZTbv4RgIyire2hAW9hprs5O/I2bituLf1Co9TivxZ7ie4T8YcOorooWhj7B8jwzYkW5byedoqrE83XkRznVT/ozR+OwDCNpKjwiODA0B3JQonTNPWFiwHkMKl4qxsywPjjRYuwrMlq38pfObG8tsB9LPvgGH6/2qyDTdCiJb7flBXDlNB3mGc3ISPt4jYnFlbwaem9c42pgv+uZA1lzsKVZTk3CpfzTwfx2aT61aI3bk80p4d/dANx3VlOa/yhJb0nEGp3mntMNyN7EZ7wgDb0ZDS6HiKW3AO6sWl6Ot7qKE61Tv4fl0qZfz2Afn2py2oHm1SOvWbj/YLT00SKWD4m/U6TAyaEUzb7OSSC9RBVbvZFnvwPKGMR4S+SDvtd6TmobC0C7zKXXn/CZD5dSOgqnRLaYiMitkhZ/KGbZO/CfCUSTQ2qztrR1CvlCpICWhMxFGw4skDZdW3b4tLtEhwrMIxdyCEZqREw3QnQuaXj4q9mNglXThWRSA5QBu2Lgkf9zp3SMmpT+/9+59qx7XnKXl36+/D5g="
  file_glob: true
  file: 
    - "target/FrameMapUtil_v*.jar"
  skip_cleanup: true
  on:
    tags: true
